apiVersion: v1
kind: Service
metadata:
    name: "kcdemo8-c714"
    labels:
        app: "kcdemo8-c714"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kcdemo8-c714"